Dependency Check

diff --git a/.github/workflows/main.yaml b/.github/workflows/main.yaml
--- a/.github/workflows/main.yaml
+++ b/.github/workflows/main.yaml
@@ -105,28 +105,38 @@ jobs:
 
       - name: Install OWASP Dependency Check
         run: |
+          sudo apt-get update
+          sudo apt-get install -y unzip default-jdk
           wget https://github.com/jeremylong/DependencyCheck/releases/download/v10.0.4/dependency-check-10.0.4-release.zip
           unzip dependency-check-10.0.4-release.zip
           sudo mv dependency-check/bin/dependency-check.sh /usr/local/bin/dependency-check
+          chmod +x /usr/local/bin/dependency-check
 
       - name: Run OWASP Dependency Check
         run: |
           mkdir -p report
-          dependency-check --project "Task-Manager-using-Flask" --scan . --out report || true
-
+          dependency-check --project "Task-Manager-using-Flask" --scan . --out report -v
+          
       - name: List current directory
-        run: |
-          ls -l
+        run: ls -l
 
       - name: List report directory
+        run: ls -l ./report
+
+      - name: Verify report files
         run: |
-          ls -l ./report
+          if [ -f report/dependency-check-report.html ]; then
+            echo "HTML report generated successfully."
+          else
+            echo "HTML report not found."
+            exit 1
+          fi
 
       - name: Upload OWASP Dependency Check reports
         uses: actions/upload-artifact@v3
         with:
           name: dependency-check-report
-          path: report/*
+          path: report/dependency-check-report.*  # Certifique-se que esse caminho está correto
 
   review:
     runs-on: ubuntu-latest
@@ -170,3 +180,19 @@ jobs:
       - name: Deploy to Staging
         run: |
           docker run -d --name Task-Manager-using-Flask -p 5000:5000 Task-Manager-using-Flask || true
+
+  prometheus:
+    runs-on: ubuntu-latest
+    needs: version-control-and-ci
+    steps:
+      - name: Checkout code
+        uses: actions/checkout@v2
+
+      - name: Run Prometheus
+        run: |
+          docker run -d \
+            --name prometheus \
+            -p 9090:9090 \
+            -v ${{ github.workspace }}/monitoring/prometheus.yml:/etc/prometheus/prometheus.yml \
+            prom/prometheus \
+            --config.file=/etc/prometheus/prometheus.yml
